[project]
name = "dc-aws-org-tools"
version = "0.0.0"
description = "For working across all AWS accounts in DC"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "boto3>=1.37.20",
    "ruff>=0.11.2",
]

[tool.uv]
package = false
required-version = "<0.6.0"

[tool.ruff]
line-length = 80
lint.ignore = ["E501"]

lint.extend-select = [
    "I",
    "C4",
    "SIM",
    "Q003",
    "RET",
]
